Repository apache/rocketmq, pull requests merged in 2019-06, with the labels that each got.

#1254 [ISSUE #1253]Add transaction namespace support
  client/src/main/java/org/apache/rocketmq/client/producer/TransactionMQProducer.java
Labels: bug

#1232 fix typo
  docs/en/Concept.md
  docs/en/architecture.md
Labels: doc

#1256 [FIX] Travis-CI Java 8 building environments.
  .travis.yml
Labels: enhancement

#1264 [ISSUE #1241]Optimize the codes for issue that suggestion about the third part dependency of the RocketMQ client.
  filter/pom.xml
  srvutil/pom.xml
  srvutil/src/main/java/org/apache/rocketmq/srvutil/FileWatchService.java
Labels: enhancement

#1260 fix typo
  store/src/main/java/org/apache/rocketmq/store/ha/HAConnection.java
  store/src/main/java/org/apache/rocketmq/store/ha/HAService.java
Labels: enhancement

#1266 Delay plant log appender in client loggger
  client/src/main/java/org/apache/rocketmq/client/log/ClientLogger.java
Labels: enhancement

#633 [ISSUE #598] Enhance transaction by putting messages that exceed max check times to system topic
  broker/src/main/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessor.java
  broker/src/main/java/org/apache/rocketmq/broker/topic/TopicConfigManager.java
  broker/src/main/java/org/apache/rocketmq/broker/transaction/AbstractTransactionalMessageCheckListener.java
  broker/src/main/java/org/apache/rocketmq/broker/transaction/queue/DefaultTransactionalMessageCheckListener.java
  broker/src/test/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessorTest.java
  broker/src/test/java/org/apache/rocketmq/broker/transaction/queue/DefaultTransactionalMessageCheckListenerTest.java
  client/src/main/java/org/apache/rocketmq/client/impl/MQClientAPIImpl.java
  client/src/test/java/org/apache/rocketmq/client/impl/MQClientAPIImplTest.java
  common/src/main/java/org/apache/rocketmq/common/MixAll.java
  common/src/main/java/org/apache/rocketmq/common/protocol/RequestCode.java
  common/src/main/java/org/apache/rocketmq/common/protocol/header/ResumeCheckHalfMessageRequestHeader.java
  pom.xml
  tools/src/main/java/org/apache/rocketmq/tools/admin/DefaultMQAdminExt.java
  tools/src/main/java/org/apache/rocketmq/tools/admin/DefaultMQAdminExtImpl.java
  tools/src/main/java/org/apache/rocketmq/tools/admin/MQAdminExt.java
  tools/src/test/java/org/apache/rocketmq/tools/command/message/QueryMsgByUniqueKeySubCommandTest.java
Labels: enhancement
