Repository apache/rocketmq, pull requests merged in 2019-01, with the labels that each got.

#648 add architecture.md
  docs/cn/architecture.md
  docs/cn/image/rocketmq_architecture_1.png
  docs/cn/image/rocketmq_architecture_2.png
  docs/cn/image/rocketmq_architecture_3.png
Labels: enhancement

#661 Add the introduction of the terminology in RocketMQ
  docs/cn/concept.md
Labels: enhancement

#537 [ISSUE #525] Support the message track
  broker/src/main/java/org/apache/rocketmq/broker/topic/TopicConfigManager.java
  client/src/main/java/org/apache/rocketmq/client/consumer/DefaultMQPushConsumer.java
  client/src/main/java/org/apache/rocketmq/client/impl/factory/MQClientInstance.java
  client/src/main/java/org/apache/rocketmq/client/producer/DefaultMQProducer.java
  client/src/main/java/org/apache/rocketmq/client/producer/TransactionMQProducer.java
  client/src/main/java/org/apache/rocketmq/client/trace/core/Utils/TrackTraceUtils.java
  client/src/main/java/org/apache/rocketmq/client/trace/core/common/TrackTraceBean.java
  client/src/main/java/org/apache/rocketmq/client/trace/core/common/TrackTraceType.java
  client/src/test/java/org/apache/rocketmq/client/impl/consumer/DefaultMQPushConsumerImplTest.java
  client/src/test/java/org/apache/rocketmq/client/impl/consumer/RebalancePushImplTest.java
  client/src/test/java/org/apache/rocketmq/client/producer/DefaultMQProducerTest.java
  client/src/test/java/org/apache/rocketmq/client/trace/DefaultMQConsumerWithTraceTest.java
  client/src/test/java/org/apache/rocketmq/client/trace/DefaultMQProducerWithTraceTest.java
  example/src/main/java/org/apache/rocketmq/example/batch/SimpleBatchProducer.java
  example/src/main/java/org/apache/rocketmq/example/batch/SplitBatchProducer.java
  example/src/main/java/org/apache/rocketmq/example/benchmark/Consumer.java
  example/src/main/java/org/apache/rocketmq/example/benchmark/Producer.java
  example/src/main/java/org/apache/rocketmq/example/broadcast/PushConsumer.java
  example/src/main/java/org/apache/rocketmq/example/filter/Consumer.java
  example/src/main/java/org/apache/rocketmq/example/filter/SqlConsumer.java
  example/src/main/java/org/apache/rocketmq/example/filter/SqlProducer.java
  example/src/main/java/org/apache/rocketmq/example/operation/Consumer.java
  example/src/main/java/org/apache/rocketmq/example/operation/Producer.java
  example/src/main/java/org/apache/rocketmq/example/ordermessage/Consumer.java
  example/src/main/java/org/apache/rocketmq/example/ordermessage/Producer.java
  example/src/main/java/org/apache/rocketmq/example/quickstart/Producer.java
  example/src/main/java/org/apache/rocketmq/example/simple/AsyncProducer.java
  example/src/main/java/org/apache/rocketmq/example/simple/Producer.java
  example/src/main/java/org/apache/rocketmq/example/simple/PushConsumer.java
  example/src/main/java/org/apache/rocketmq/example/simple/TestProducer.java
  example/src/main/java/org/apache/rocketmq/example/tracemessage/TraceProducer.java
  example/src/main/java/org/apache/rocketmq/example/tracemessage/TracePushConsumer.java
  tools/src/main/java/org/apache/rocketmq/tools/command/broker/SendMsgStatusCommand.java
Labels: new feature, rip

#707 [RIP-9]add the msg trace and acl feature content of RocketMQ doc part.
  docs/cn/acl/user_guide.md
  docs/cn/msg_trace/user_guide.md
Labels: enhancement

#620 [ISSUE #608] Polish filter example
  example/src/main/java/org/apache/rocketmq/example/filter/SqlFilterConsumer.java
  example/src/main/java/org/apache/rocketmq/example/filter/SqlFilterProducer.java
  example/src/main/java/org/apache/rocketmq/example/filter/SqlProducer.java
  example/src/main/java/org/apache/rocketmq/example/filter/TagFilterConsumer.java
  example/src/main/java/org/apache/rocketmq/example/filter/TagFilterProducer.java
Labels: bug, enhancement

#708 [RIP-9]modify the architecture part Develop
  docs/cn/architecture.md
Labels: enhancement

#716 [RIP-9]adjust the formate of RocketMQ acl doc part.
  docs/cn/acl/user_guide.md
Labels: enhancement

#654 [RIP-9]Add the operation part
  docs/cn/operation.md
Labels: enhancement

#717 [RIP-9]Add the best practice of RocketMQ
  docs/cn/best_practice.md
Labels: enhancement

#725 [ISSUE#724]Integrate Acl for snode branch.
  acl/pom.xml
  distribution/conf/plain_acl.yml
  example/src/main/java/org/apache/rocketmq/example/filter/SqlConsumer.java
  pom.xml
  remoting/src/main/java/org/apache/rocketmq/remoting/common/RemotingUtil.java
  remoting/src/main/java/org/apache/rocketmq/remoting/util/ServiceProvider.java
  snode/pom.xml
  snode/src/main/java/org/apache/rocketmq/snode/SnodeController.java
  snode/src/main/java/org/apache/rocketmq/snode/config/SnodeConfig.java
  snode/src/main/java/org/apache/rocketmq/snode/flowcontrol/QPSFlowControlServiceImpl.java
  snode/src/main/resources/META-INF/service/org.apache.rocketmq.acl.AccessValidator
  snode/src/test/java/org/apache/rocketmq/snode/SnodeControllerTest.java
  snode/src/test/resources/META-INF/service/flowControl.yml
  snode/src/test/resources/META-INF/service/org.apache.rocketmq.acl.AccessValidator
  snode/src/test/resources/META-INF/service/org.apache.rocketmq.snode.interceptor.ConsumeMessageInterceptor
  snode/src/test/resources/META-INF/service/org.apache.rocketmq.snode.interceptor.RemotingServerInterceptor
  snode/src/test/resources/META-INF/service/org.apache.rocketmq.snode.interceptor.SendMessageInterceptor
Labels: enhancement

#738 [ISSUE #737]Send and consumer messages by linking to snodes
  client/src/main/java/org/apache/rocketmq/client/exception/MQSnodeException.java
  client/src/main/java/org/apache/rocketmq/client/impl/MQClientAPIImpl.java
  client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultMQPushConsumerImpl.java
  client/src/main/java/org/apache/rocketmq/client/impl/consumer/PullAPIWrapper.java
  client/src/main/java/org/apache/rocketmq/client/impl/factory/MQClientInstance.java
  client/src/main/java/org/apache/rocketmq/client/impl/producer/DefaultMQProducerImpl.java
  example/src/main/java/org/apache/rocketmq/example/quickstart/Producer.java
Labels: new feature
