Repository apache/rocketmq, pull requests merged in 2019-09, with the labels that each got.

#1444 [ISSUES #1439]fix transaction typo
  docs/cn/README.md
  docs/cn/concept.md
Labels: bug

#1460 [ISSUE #1435]Fix discarded mqadmin subcommand document description
  docs/cn/operation.md
Labels: doc

#1455 [ISSUE #1456]Fix replica abnormal recover slow issue
  store/src/main/java/org/apache/rocketmq/store/ConsumeQueue.java
Labels: bug, enhancement

#1438 fix typo
  docs/en/Configuration_Client.md
  openmessaging/src/main/java/io/openmessaging/rocketmq/consumer/LocalMessageCache.java
  openmessaging/src/main/java/io/openmessaging/rocketmq/consumer/PullConsumerImpl.java
  remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingServer.java
Labels: enhancement

#1109 [ISSUE #1108] Fix concurrent problems with client-side connection creation
  remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingClient.java
Labels: bug

#1461 Fix(client): lite pull consumer lost messages in some scenario
  client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultLitePullConsumerImpl.java
Labels: bug
