Repository apache/rocketmq, pull requests merged in 2019-04, with the labels that each got.

#1079 [ISSUE #1078]fix User can't use mqadmin command normally if they don't copy the tool.yml file to related fold and AclEnable flag is closed.
  acl/src/main/java/org/apache/rocketmq/acl/common/AclUtils.java
  acl/src/test/java/org/apache/rocketmq/acl/common/AclUtilsTest.java
  acl/src/test/resources/conf/plain_acl_format_error.yml
  tools/src/main/java/org/apache/rocketmq/tools/command/MQAdminStartup.java
Labels: enhancement

#1129 Change the release package style to rocketmq-{version}
  distribution/pom.xml
  distribution/release-client.xml
  distribution/release.xml
Labels: enhancement

#1158 [graal] Successfully run with main method
  client/config/reflect-config.json
  client/src/main/java/org/apache/rocketmq/client/Producer.java
  client/svm.sh
Labels: new feature

#1122 [ISSUE #1120]Add new feature: support namespace
  broker/src/main/java/org/apache/rocketmq/broker/mqtrace/ConsumeMessageContext.java
  broker/src/main/java/org/apache/rocketmq/broker/mqtrace/SendMessageContext.java
  broker/src/main/java/org/apache/rocketmq/broker/processor/AbstractSendMessageProcessor.java
  broker/src/main/java/org/apache/rocketmq/broker/processor/SendMessageProcessor.java
  client/src/main/java/org/apache/rocketmq/client/ClientConfig.java
  client/src/main/java/org/apache/rocketmq/client/consumer/DefaultMQPullConsumer.java
  client/src/main/java/org/apache/rocketmq/client/consumer/DefaultMQPushConsumer.java
  client/src/main/java/org/apache/rocketmq/client/hook/ConsumeMessageContext.java
  client/src/main/java/org/apache/rocketmq/client/hook/SendMessageContext.java
  client/src/main/java/org/apache/rocketmq/client/impl/ClientRemotingProcessor.java
  client/src/main/java/org/apache/rocketmq/client/impl/MQAdminImpl.java
  client/src/main/java/org/apache/rocketmq/client/impl/MQClientAPIImpl.java
  client/src/main/java/org/apache/rocketmq/client/impl/consumer/ConsumeMessageConcurrentlyService.java
  client/src/main/java/org/apache/rocketmq/client/impl/consumer/ConsumeMessageOrderlyService.java
  client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultMQPullConsumerImpl.java
  client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultMQPushConsumerImpl.java
  client/src/main/java/org/apache/rocketmq/client/impl/factory/MQClientInstance.java
  client/src/main/java/org/apache/rocketmq/client/impl/producer/DefaultMQProducerImpl.java
  client/src/main/java/org/apache/rocketmq/client/producer/DefaultMQProducer.java
  client/src/main/java/org/apache/rocketmq/client/producer/TransactionMQProducer.java
  common/pom.xml
  common/src/main/java/org/apache/rocketmq/common/message/Message.java
  common/src/main/java/org/apache/rocketmq/common/message/MessageConst.java
  common/src/main/java/org/apache/rocketmq/common/protocol/NamespaceUtil.java
  common/src/test/java/org/apache/rocketmq/common/protocol/NamespaceUtilTest.java
  example/src/main/java/org/apache/rocketmq/example/namespace/ProducerWithNamespace.java
  example/src/main/java/org/apache/rocketmq/example/namespace/PullConsumerWithNamespace.java
  example/src/main/java/org/apache/rocketmq/example/namespace/PushConsumerWithNamespace.java
Labels: enhancement

#1175 [ISSUE #1147]Add name server domain host support
  client/src/main/java/org/apache/rocketmq/client/ClientConfig.java
  common/src/main/java/org/apache/rocketmq/common/utils/NameServerAddressUtils.java
Labels: enhancement

#1181 [ISSUE #1164]Fix Consumer Instance can't consume message from slave when cluster is in the high level tps and master has been killed.
  store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java
Labels: bug
