Repository apache/rocketmq, pull requests merged in 2019-10, with the labels that each got.

#1532 [ISSUE #1531]Upgrade fastjson version
  README.md
  pom.xml
Labels: bug, enhancement

#1536 [ISSUE #1535] Fix ha sync transfer timeout
  store/src/main/java/org/apache/rocketmq/store/ha/HAService.java
Labels: bug, enhancement

#1529 [ISSUE #1528] mocking related functions to make producer get right topicrouteinfo and invoke callback functions
  client/src/test/java/org/apache/rocketmq/client/producer/DefaultMQProducerTest.java
Labels: enhancement

#952 [RIP-10] Add test cases for ConsumeMessageOrderlyService#consumeMessageDirectly
  client/src/test/java/org/apache/rocketmq/client/impl/consumer/ConsumeMessageOrderlyServiceTest.java
Labels: enhancement

#1553 [ISSUE #1526]modify docs-cn description error
  docs/cn/README
  docs/cn/features.md
Labels: doc

#1544 [ISSUE #1519]Optimise performance/stability of transaction message
  broker/src/main/java/org/apache/rocketmq/broker/processor/EndTransactionProcessor.java
  broker/src/main/java/org/apache/rocketmq/broker/transaction/AbstractTransactionalMessageCheckListener.java
  broker/src/main/java/org/apache/rocketmq/broker/transaction/queue/TransactionalMessageBridge.java
  broker/src/main/java/org/apache/rocketmq/broker/transaction/queue/TransactionalMessageServiceImpl.java
  example/src/main/java/org/apache/rocketmq/example/benchmark/Consumer.java
  example/src/main/java/org/apache/rocketmq/example/benchmark/TransactionProducer.java
Labels: enhancement

#1556 fix cacography
  docs/cn/README.md
Labels: doc
