Repository apache/rocketmq, pull requests merged in 2020-01, with the labels that each got.

#1636 [ISSUE #1110] Fix wrong topic max length in rocketmq client.
  client/src/main/java/org/apache/rocketmq/client/Validators.java
  client/src/test/java/org/apache/rocketmq/client/ValidatorsTest.java
Labels: enhancement

#1303 [ISSSUE #1188]Fix the problem when more than one producer or consumer in the same process can trace only one
  client/src/main/java/org/apache/rocketmq/client/consumer/DefaultMQPushConsumer.java
  client/src/main/java/org/apache/rocketmq/client/producer/DefaultMQProducer.java
  client/src/main/java/org/apache/rocketmq/client/trace/AsyncTraceDispatcher.java
  client/src/main/java/org/apache/rocketmq/client/trace/TraceConstants.java
  client/src/main/java/org/apache/rocketmq/client/trace/TraceDispatcher.java
Labels: enhancement

#1625 [ISSUE #1639] use ipv4 first when choosing local IP
  common/src/main/java/org/apache/rocketmq/common/UtilAll.java
Labels: enhancement

#1629 [ISSUE #1620]fix #1620 amout spell error
  tools/src/main/java/org/apache/rocketmq/tools/command/cluster/CLusterSendMsgRTCommand.java
  tools/src/main/java/org/apache/rocketmq/tools/command/message/CheckMsgSendRTCommand.java
Labels: enhancement

#1702 [ISSUE #1701] Delete invalid method to get next pullBatchSize
  client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultLitePullConsumerImpl.java
Labels: enhancement

#1705 [ISSUE #1706]feat(pull_consumer) refactor the consumer offset update logic
  client/src/main/java/org/apache/rocketmq/client/consumer/DefaultLitePullConsumer.java
  client/src/main/java/org/apache/rocketmq/client/impl/consumer/AssignedMessageQueue.java
  client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultLitePullConsumerImpl.java
Labels: enhancement

#1627 [for 4.6.0] Fix concurrent problem in ProducerManager.getAvaliableCha…
  broker/src/main/java/org/apache/rocketmq/broker/client/ProducerManager.java
  broker/src/main/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessor.java
  broker/src/test/java/org/apache/rocketmq/broker/client/ProducerManagerTest.java
  broker/src/test/java/org/apache/rocketmq/broker/processor/ClientManageProcessorTest.java
Labels: enhancement

#1649 [ISSUE #1648]Fix the send back message treated as transaction message
  broker/src/main/java/org/apache/rocketmq/broker/processor/EndTransactionProcessor.java
  broker/src/main/java/org/apache/rocketmq/broker/processor/SendMessageProcessor.java
  client/src/main/java/org/apache/rocketmq/client/impl/consumer/ConsumeMessageOrderlyService.java
  client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultMQPushConsumerImpl.java
Labels: bug, enhancement

#1704 [ISSUE #1656] Fix StatsItem bug
  common/src/main/java/org/apache/rocketmq/common/stats/StatsItem.java
  common/src/test/java/org/apache/rocketmq/common/stats/StatsItemSetTest.java
Labels: bug

#1723 [ISSUE # 1724]typo fix
  client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultLitePullConsumerImpl.java
Labels: enhancement

#1646 correct spelling
  store/src/main/java/org/apache/rocketmq/store/CommitLog.java
Labels: enhancement

#1683 optimise benchmark consumer, add consume fail rate option
  example/src/main/java/org/apache/rocketmq/example/benchmark/Consumer.java
Labels: enhancement
