Repository apache/rocketmq, pull requests merged in 2020-04, with the labels that each got.

#1860 [ISSUE #1859] add codecov report for tests.
  .travis.yml
  README.md
  pom.xml
Labels: doc

#1899 [ISSUE #1463] Skip encode the null value property as string "null"
  common/src/main/java/org/apache/rocketmq/common/message/MessageDecoder.java
  common/src/test/java/org/apache/rocketmq/common/message/MessageDecoderTest.java
Labels: enhancement

#1911 [ISSUE #1912]Polish the commited offset logic
  client/src/main/java/org/apache/rocketmq/client/consumer/DefaultLitePullConsumer.java
  client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultLitePullConsumerImpl.java
Labels: bug

#1965 [ISSUE #1964]fix Doc error: Connection related command instructions
  docs/cn/operation.md
  docs/en/CLITools.md
Labels: doc

#1905 [ISSUE #1906] The BooleanConstantExpression might lead to class loading deadlock
  filter/src/main/java/org/apache/rocketmq/filter/expression/BooleanConstantExpression.java
  filter/src/main/java/org/apache/rocketmq/filter/expression/ComparisonExpression.java
  filter/src/main/java/org/apache/rocketmq/filter/expression/ConstantExpression.java
  filter/src/main/java/org/apache/rocketmq/filter/parser/SelectorParser.java
Labels: broker, enhancement
