Repository apache/rocketmq, pull requests merged in 2020-02, with the labels that each got.

#1758 [ISSUE #1751]Fix bug in MessageClientIDSetter
  common/src/main/java/org/apache/rocketmq/common/message/MessageClientIDSetter.java
  common/src/test/java/org/apache/rocketmq/common/message/MessageClientIDSetterTest.java
Labels: bug

#1772 [ISSUE #1771]add MessageExt.getBrokerName for issue
  client/src/main/java/org/apache/rocketmq/client/impl/consumer/PullAPIWrapper.java
  common/src/main/java/org/apache/rocketmq/common/message/MessageExt.java
Labels: enhancement

#1775 min value for autoCommitIntervalMillis. #1774
  client/src/main/java/org/apache/rocketmq/client/consumer/DefaultLitePullConsumer.java
Labels: enhancement

#1783 Improve exception handle of transaction check service
  broker/src/main/java/org/apache/rocketmq/broker/transaction/queue/TransactionalMessageServiceImpl.java
Labels: enhancement

#1793 [ISSUE #1787] Fix the issue that queryCq command of mqadmin returned incorrect data
  broker/src/main/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessor.java
Labels: bug

#1795 [ISSUE #1794] Upgrade fastjson version
  pom.xml
Labels: enhancement

#1804 fix(pull_schedual) add the namespace wrapper in callback
  client/src/main/java/org/apache/rocketmq/client/consumer/MQPullConsumerScheduleService.java
Labels: bug

#1800 [ISSUE #1781]Fix asynchronous send retry
  client/src/main/java/org/apache/rocketmq/client/impl/MQClientAPIImpl.java
  remoting/src/main/java/org/apache/rocketmq/remoting/protocol/RemotingCommand.java
Labels: bug, enhancement
