Repository apache/rocketmq, pull requests merged in 2021-06, with the labels that each got.

#2991 [ISSUE #2990] Add message tracing switch in sendMessage command of mqadmin
  tools/src/main/java/org/apache/rocketmq/tools/command/message/SendMessageCommand.java
Labels: wip

#2888 [ISSUE #2883] [Part D] Improve produce performance in M/S mode.
  common/src/main/java/org/apache/rocketmq/common/BrokerConfig.java
  store/src/main/java/org/apache/rocketmq/store/config/MessageStoreConfig.java
Labels: wip

#3020 [ISSUE 3019] Fixed bug with batch-sent message statistics
  store/src/main/java/org/apache/rocketmq/store/dledger/DLedgerCommitLog.java
Labels: bug

#2876 [ISSUE #2873] add benchmark for batch message
  distribution/benchmark/batchproducer.sh
  example/src/main/java/org/apache/rocketmq/example/benchmark/BatchProducer.java
Labels: test, wip

#3069 [ISSUE #3068] remove jaeger tracing dependency in release
  distribution/release.xml
Labels: wip

#2989 [ISSUE #2988] Fix fail to send trace of last message before shutting down producer
  client/src/main/java/org/apache/rocketmq/client/trace/AsyncTraceDispatcher.java
Labels: wip

#3088 [Doc] wrong word in design.md
  docs/cn/design.md
Labels: doc
