Repository apache/rocketmq, pull requests merged in 2021-07, with the labels that each got.

#3113 [ISSUE #3109]Return unknown cmd
  broker/src/main/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessor.java
Labels: enhancement

#2882 [ISSUE #3112]Fix: update the option's description of delete/update access config command
  example/src/main/java/org/apache/rocketmq/example/benchmark/Consumer.java
  tools/src/main/java/org/apache/rocketmq/tools/command/acl/DeleteAccessConfigSubCommand.java
  tools/src/main/java/org/apache/rocketmq/tools/command/acl/UpdateAccessConfigSubCommand.java
Labels: wip

#2885 [ISSUE #2883] [Part B] Improve produce performance in M/S mode.
  store/src/main/java/org/apache/rocketmq/store/CommitLog.java
  store/src/main/java/org/apache/rocketmq/store/ha/HAService.java
  store/src/main/java/org/apache/rocketmq/store/ha/WaitNotifyObject.java
Labels: enhancement

#2886 [ISSUE #2883] [Part C] Improve produce performance in M/S mode.
  broker/src/main/java/org/apache/rocketmq/broker/plugin/AbstractPluginMessageStore.java
  store/src/main/java/org/apache/rocketmq/store/CommitLog.java
  store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java
  store/src/main/java/org/apache/rocketmq/store/MessageStore.java
  store/src/main/java/org/apache/rocketmq/store/dledger/DLedgerCommitLog.java
  store/src/main/java/org/apache/rocketmq/store/ha/HAService.java
Labels: enhancement

#3125 [ISSUE #3099] Fix the incorrect judegment  'writePos - lastCommittedPosition > commitLeastPages' in the method 'commit0' of class 'MappedFile'
  store/src/main/java/org/apache/rocketmq/store/MappedFile.java
Labels: bug

#3122 [ISSUE #3123]fix namesrv endpoint
  client/src/main/java/org/apache/rocketmq/client/ClientConfig.java
  common/src/main/java/org/apache/rocketmq/common/utils/NameServerAddressUtils.java
Labels: client, enhancement

#3056 [ISSUES #3055]add some doc of the API_Reference_DefaultMQProducer of English.
  docs/en/client/java/API_Reference_DefaultMQProducer.md
Labels: doc

#3157 [ISSUE #3154 ]delete the unuse code
  client/src/main/java/org/apache/rocketmq/client/impl/consumer/ConsumeMessageConcurrentlyService.java
Labels: code style

#3047 [ISSUE #3046]:Polish lite pull consumer code style
  client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultLitePullConsumerImpl.java
Labels: client, code style

#3158 [ISSUE #2708] fix offset rollback when fetch offset from broker exception
  client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultLitePullConsumerImpl.java
  client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultMQPushConsumerImpl.java
  client/src/main/java/org/apache/rocketmq/client/impl/consumer/RebalanceImpl.java
  client/src/main/java/org/apache/rocketmq/client/impl/consumer/RebalanceLitePullImpl.java
Labels: bug, client, wip

#2058 [ISSUE #2055] Fix NPE in SendMessageProcessor.handleRetryAndDLQ
  broker/src/main/java/org/apache/rocketmq/broker/processor/SendMessageProcessor.java
Labels: wip

#2995 [ISSUE #2990] Add message tracing switch in sendMessage command of mqadmin, and add document
  docs/cn/msg_trace/user_guide.md
  docs/en/msg_trace/user_guide.md
Labels: doc

#3032 [ISSUE #3031] Upgrade netty-all dependency version to 4.1.65.Final
  broker/src/main/java/org/apache/rocketmq/broker/pagecache/ManyMessageTransfer.java
  broker/src/main/java/org/apache/rocketmq/broker/pagecache/OneMessageTransfer.java
  broker/src/main/java/org/apache/rocketmq/broker/pagecache/QueryMessageTransfer.java
  pom.xml
  remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyLogger.java
Labels: enhancement, remoting

#2889 [ISSUE #2883] [Part E] Improve produce performance in M/S mode.
  store/src/main/java/org/apache/rocketmq/store/AppendMessageCallback.java
  store/src/main/java/org/apache/rocketmq/store/AppendMessageResult.java
  store/src/main/java/org/apache/rocketmq/store/CommitLog.java
  store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java
  store/src/main/java/org/apache/rocketmq/store/MappedFile.java
  store/src/main/java/org/apache/rocketmq/store/MessageExtBrokerInner.java
  store/src/main/java/org/apache/rocketmq/store/dledger/DLedgerCommitLog.java
  store/src/test/java/org/apache/rocketmq/store/AppendCallbackTest.java
Labels: enhancement
