Repository apache/rocketmq, pull requests merged in 2021-09, with the labels that each got.

#3334 [ISSUE #3333] Remove commons-codes dependency
  client/pom.xml
  client/src/main/java/org/apache/rocketmq/client/trace/TraceView.java
  client/src/test/java/org/apache/rocketmq/client/trace/TraceViewTest.java
Labels: wip

#3339 [ISSUE #3339] (doc)fix typo in update operation.md
  docs/cn/operation.md
  docs/en/operation.md
Labels: doc

#3325 [ISSUE #3326] fix send trace fail if broker set tls.server.mode=enforcing
  client/src/main/java/org/apache/rocketmq/client/consumer/DefaultLitePullConsumer.java
  client/src/main/java/org/apache/rocketmq/client/consumer/DefaultMQPushConsumer.java
  client/src/main/java/org/apache/rocketmq/client/producer/DefaultMQProducer.java
  client/src/test/java/org/apache/rocketmq/client/trace/DefaultMQConsumerWithTraceTest.java
  client/src/test/java/org/apache/rocketmq/client/trace/DefaultMQLitePullConsumerWithTraceTest.java
  client/src/test/java/org/apache/rocketmq/client/trace/DefaultMQProducerWithTraceTest.java
Labels: bug, wip

#3302 [ISSUE] Add get stats and single queue stats for schedule topic
  broker/src/main/java/org/apache/rocketmq/broker/processor/SendMessageProcessor.java
  common/src/main/java/org/apache/rocketmq/common/MixAll.java
  store/src/main/java/org/apache/rocketmq/store/schedule/ScheduleMessageService.java
  store/src/main/java/org/apache/rocketmq/store/stats/BrokerStatsManager.java
  store/src/test/java/stats/BrokerStatsManagerTest.java
Labels: enhancement, broker, wip

#3220 [ISSUE #3225]change Random to ThreadLocalRandom in broker
  broker/src/main/java/org/apache/rocketmq/broker/processor/AbstractSendMessageProcessor.java
  broker/src/main/java/org/apache/rocketmq/broker/processor/ReplyMessageProcessor.java
  broker/src/main/java/org/apache/rocketmq/broker/processor/SendMessageProcessor.java
  broker/src/main/java/org/apache/rocketmq/broker/transaction/AbstractTransactionalMessageCheckListener.java
  broker/src/main/java/org/apache/rocketmq/broker/transaction/queue/DefaultTransactionalMessageCheckListener.java
Labels: enhancement

#3280 [ISSUE #3281 ][acl] fix fail to delete topic perm list and global white address(#3128)
  acl/src/main/java/org/apache/rocketmq/acl/plain/PlainPermissionManager.java
  acl/src/test/java/org/apache/rocketmq/acl/plain/PlainAccessValidatorTest.java
  broker/src/main/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessor.java
  client/src/main/java/org/apache/rocketmq/client/impl/MQClientAPIImpl.java
  common/src/main/java/org/apache/rocketmq/common/UtilAll.java
  common/src/test/java/org/apache/rocketmq/common/UtilAllTest.java
  tools/src/main/java/org/apache/rocketmq/tools/command/acl/DeleteAccessConfigSubCommand.java
  tools/src/main/java/org/apache/rocketmq/tools/command/acl/UpdateGlobalWhiteAddrSubCommand.java
Labels: wip

#3351 [ISSUE 3194] [PART C] Replace AtomicLong with LongAdder in StatsItem.java to improve performance
  client/src/test/java/org/apache/rocketmq/client/impl/consumer/ConsumeMessageConcurrentlyServiceTest.java
  common/src/main/java/org/apache/rocketmq/common/stats/StatsItem.java
  common/src/main/java/org/apache/rocketmq/common/stats/StatsItemSet.java
  common/src/test/java/org/apache/rocketmq/common/stats/StatsItemSetTest.java
  store/src/main/java/org/apache/rocketmq/store/stats/BrokerStatsManager.java
  store/src/test/java/org/apache/rocketmq/store/schedule/ScheduleMessageServiceTest.java
Labels: wip

#2437 [ISSUE #2436] DLQ topic default perm change
  broker/src/main/java/org/apache/rocketmq/broker/processor/SendMessageProcessor.java
Labels: wip

#3295 [ISSUE #3308] production level pull api demo
  example/src/main/java/org/apache/rocketmq/example/simple/PullConsumer.java
Labels: enhancement

#3358 [ISSUE #1869] Delay message can't be consumed when delay offset in delayOffset.json is wrong
  common/src/main/java/org/apache/rocketmq/common/stats/StatsItem.java
  store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java
  store/src/main/java/org/apache/rocketmq/store/schedule/ScheduleMessageService.java
  store/src/test/java/org/apache/rocketmq/store/ScheduleMessageServiceTest.java
Labels: bug, broker

#3357 RIP-7 Multiple Directories Storage Support
  broker/src/main/java/org/apache/rocketmq/broker/processor/SendMessageProcessor.java
  common/src/main/java/org/apache/rocketmq/common/UtilAll.java
  store/src/main/java/org/apache/rocketmq/store/CommitLog.java
  store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java
  store/src/main/java/org/apache/rocketmq/store/MappedFileQueue.java
  store/src/main/java/org/apache/rocketmq/store/MultiPathMappedFileQueue.java
  store/src/main/java/org/apache/rocketmq/store/config/MessageStoreConfig.java
  store/src/test/java/org/apache/rocketmq/store/DefaultMessageStoreCleanFilesTest.java
  store/src/test/java/org/apache/rocketmq/store/MultiPathMappedFileQueueTest.java
Labels: enhancement, wip

#3385 [ISSUE #3384] Add SendBack message to SCHEDULE_TOPIC_XXXX stats
  broker/src/main/java/org/apache/rocketmq/broker/processor/SendMessageProcessor.java
Labels: enhancement
