Repository apache/rocketmq, pull requests merged in 2021-12, with the labels that each got.

#3557 [ISSUE #3550] doc:fix typo in readme
  README.md
Labels: doc

#3479 [Issue #3476] Fix last separator of properties string is missing when using batch send
  store/src/main/java/org/apache/rocketmq/store/CommitLog.java
  store/src/test/java/org/apache/rocketmq/store/BatchPutMessageTest.java
Labels: bug

#3395 [ISSUE #3394] fix duplicate keys in trace message
  client/src/main/java/org/apache/rocketmq/client/trace/TraceDataEncoder.java
  client/src/test/java/org/apache/rocketmq/client/trace/TraceDataEncoderTest.java
Labels: wip

#3652 [ISSUE #3651] for add netty channel option WRITE_BUFFER_WATER_MARK
  remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyClientConfig.java
  remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingClient.java
  remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingServer.java
  remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyServerConfig.java
  remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettySystemConfig.java
Labels: enhancement, remoting

#1098 [ISSUE #1097]Fix null pointer problem when consumption start time is null
  client/src/main/java/org/apache/rocketmq/client/impl/consumer/ProcessQueue.java
Labels: enhancement

#3616 [ISSUE 3613] bug fix, solve message hash conflict in index file
  client/src/main/java/org/apache/rocketmq/client/impl/MQAdminImpl.java
  test/src/test/java/org/apache/rocketmq/test/base/BaseConf.java
  test/src/test/java/org/apache/rocketmq/test/client/producer/querymsg/QueryMsgByKeyIT.java
Labels: bug

#3663 Fix spelling error in DefaultMessageStore
  store/src/main/java/org/apache/rocketmq/store/CommitLog.java
  store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java
Labels: code style

#1764 Optimize RemotingHelper#parseSocketAddressAddr
  remoting/src/main/java/org/apache/rocketmq/remoting/common/RemotingHelper.java
Labels: enhancement
