Repository apache/rocketmq, pull requests merged in 2021-05, with the labels that each got.

#2861 [ISSUE #2860] support opentracing for rocketmq client
  client/pom.xml
  client/src/main/java/org/apache/rocketmq/client/trace/TraceConstants.java
  client/src/main/java/org/apache/rocketmq/client/trace/hook/ConsumeMessageOpenTracingHookImpl.java
  client/src/main/java/org/apache/rocketmq/client/trace/hook/EndTransactionOpenTracingHookImpl.java
  client/src/main/java/org/apache/rocketmq/client/trace/hook/SendMessageOpenTracingHookImpl.java
  client/src/test/java/org/apache/rocketmq/client/trace/DefaultMQConsumerWithOpenTracingTest.java
  client/src/test/java/org/apache/rocketmq/client/trace/DefaultMQProducerWithOpenTracingTest.java
  client/src/test/java/org/apache/rocketmq/client/trace/TransactionMQProducerWithOpenTracingTest.java
  example/pom.xml
  example/src/main/java/org/apache/rocketmq/example/tracemessage/OpenTracingProducer.java
  example/src/main/java/org/apache/rocketmq/example/tracemessage/OpenTracingPushConsumer.java
  example/src/main/java/org/apache/rocketmq/example/tracemessage/OpenTracingTransactionProducer.java
Labels: wip

#2866 [ISSUE #2865] Batch message send bug fix
  store/src/main/java/org/apache/rocketmq/store/dledger/DLedgerCommitLog.java
Labels: broker, store, wip

#1177 [ISSUE #1057]Filter out docker0 when finding a local address
  remoting/src/main/java/org/apache/rocketmq/remoting/common/RemotingUtil.java
Labels: enhancement

#1378 Fix some code style issue and remove redundant code
  acl/src/main/java/org/apache/rocketmq/acl/plain/RemoteAddressStrategyFactory.java
  broker/src/main/java/org/apache/rocketmq/broker/mqtrace/SendMessageHook.java
  broker/src/test/java/org/apache/rocketmq/broker/BrokerOuterAPITest.java
  common/src/main/java/org/apache/rocketmq/common/hook/FilterCheckHook.java
  filter/src/main/java/org/apache/rocketmq/filter/parser/SimpleCharStream.java
  logging/src/main/java/org/apache/rocketmq/logging/inner/Level.java
  test/src/main/java/org/apache/rocketmq/test/util/FileUtil.java
  test/src/main/java/org/apache/rocketmq/test/util/MQWait.java
  test/src/main/java/org/apache/rocketmq/test/util/RandomUtil.java
  test/src/main/java/org/apache/rocketmq/test/util/RandomUtils.java
  test/src/main/java/org/apache/rocketmq/test/util/VerifyUtils.java
  test/src/test/java/org/apache/rocketmq/test/client/consumer/tag/MulTagSubIT.java
  test/src/test/java/org/apache/rocketmq/test/client/consumer/tag/TagMessageWithMulConsumerIT.java
  tools/src/main/java/org/apache/rocketmq/tools/command/cluster/CLusterSendMsgRTCommand.java
Labels: enhancement

#1393 fixed startup script on windows
  distribution/bin/runbroker.cmd
  distribution/bin/runserver.cmd
Labels: enhancement

#2684 [ISSUE #2683] Add delay message stats to brokerStatsManager
  store/src/main/java/org/apache/rocketmq/store/config/MessageStoreConfig.java
  store/src/main/java/org/apache/rocketmq/store/schedule/ScheduleMessageService.java
  store/src/test/java/org/apache/rocketmq/store/schedule/ScheduleMessageServiceTest.java
Labels: wip

#2418 [ISSUE #2328] Add parameter validation to ACL
  acl/src/main/java/org/apache/rocketmq/acl/common/AclConstants.java
  acl/src/main/java/org/apache/rocketmq/acl/common/Permission.java
  acl/src/main/java/org/apache/rocketmq/acl/plain/PlainPermissionManager.java
  acl/src/test/java/org/apache/rocketmq/acl/common/PermissionTest.java
  acl/src/test/java/org/apache/rocketmq/acl/plain/PlainAccessValidatorTest.java
Labels: wip

#2518 [ISSUE #2357] Reload the delay offset when ScheduleMessageService start
  store/src/main/java/org/apache/rocketmq/store/schedule/ScheduleMessageService.java
Labels: wip

#2927 [ISSUE #2926] fix fast-try.sh fail to run in ubuntu
  distribution/bin/dledger/fast-try.sh
Labels: enhancement, wip
