Repository apache/rocketmq, pull requests merged in 2022-08, with the labels that each got.

#4753 [ISSUE #4725] Optimize the CK/ACK 's invisibleTime in POP consumption mode.
  broker/src/main/java/org/apache/rocketmq/broker/BrokerController.java
  broker/src/main/java/org/apache/rocketmq/broker/processor/AckMessageProcessor.java
  broker/src/main/java/org/apache/rocketmq/broker/processor/ChangeInvisibleTimeProcessor.java
  broker/src/main/java/org/apache/rocketmq/broker/processor/PopBufferMergeService.java
  broker/src/main/java/org/apache/rocketmq/broker/processor/PopMessageProcessor.java
  broker/src/main/java/org/apache/rocketmq/broker/processor/PopReviveService.java
  broker/src/main/java/org/apache/rocketmq/broker/util/MsgUtil.java
  broker/src/test/java/org/apache/rocketmq/broker/processor/AckMessageProcessorTest.java
  broker/src/test/java/org/apache/rocketmq/broker/processor/ChangeInvisibleTimeProcessorTest.java
  broker/src/test/java/org/apache/rocketmq/broker/processor/PopMessageProcessorTest.java
  broker/src/test/java/org/apache/rocketmq/broker/processor/PopReviveServiceTest.java
  common/src/main/java/org/apache/rocketmq/common/message/Message.java
  docs/cn/controller/quick_start.md
  example/src/main/java/org/apache/rocketmq/example/filter/TagFilterConsumer.java
Labels: type/enhancement

#4383 [ISSUE #4382]Namesrv nearby route
  broker/src/main/java/org/apache/rocketmq/broker/out/BrokerOuterAPI.java
  client/src/main/java/org/apache/rocketmq/client/impl/MQClientAPIImpl.java
  common/src/main/java/org/apache/rocketmq/common/MixAll.java
  common/src/main/java/org/apache/rocketmq/common/protocol/route/BrokerData.java
  common/src/main/java/org/apache/rocketmq/common/rpchook/DynamicalExtFieldRPCHook.java
  namesrv/src/main/java/org/apache/rocketmq/namesrv/NamesrvController.java
  namesrv/src/main/java/org/apache/rocketmq/namesrv/NamesrvStartup.java
  namesrv/src/main/java/org/apache/rocketmq/namesrv/processor/DefaultRequestProcessor.java
  namesrv/src/main/java/org/apache/rocketmq/namesrv/route/ZoneRouteRPCHook.java
  namesrv/src/main/java/org/apache/rocketmq/namesrv/routeinfo/RouteInfoManager.java
  namesrv/src/test/java/org/apache/rocketmq/namesrv/processor/RequestProcessorTest.java
  namesrv/src/test/java/org/apache/rocketmq/namesrv/routeinfo/GetRouteInfoBenchmark.java
  namesrv/src/test/java/org/apache/rocketmq/namesrv/routeinfo/RegisterBrokerBenchmark.java
  namesrv/src/test/java/org/apache/rocketmq/namesrv/routeinfo/RouteInfoManagerTest.java
  namesrv/src/test/java/org/apache/rocketmq/namesrv/routeinfo/RouteInfoManagerTestBase.java
  namesrv/src/test/java/org/apache/rocketmq/namesrv/routeinfo/RouteInfoManager_NewTest.java
Labels: module/namesrv, type/new feature

#4822 [ISSUE #4821] Add some integration tests for POP consumption in slave-acting-master mode
  broker/src/main/java/org/apache/rocketmq/broker/processor/ChangeInvisibleTimeProcessor.java
  broker/src/main/java/org/apache/rocketmq/broker/processor/PopBufferMergeService.java
  broker/src/main/java/org/apache/rocketmq/broker/processor/PopMessageProcessor.java
  broker/src/main/java/org/apache/rocketmq/broker/processor/PopReviveService.java
  broker/src/test/java/org/apache/rocketmq/broker/processor/ChangeInvisibleTimeProcessorTest.java
  broker/src/test/java/org/apache/rocketmq/broker/processor/PopMessageProcessorTest.java
  test/src/test/java/org/apache/rocketmq/test/container/PopSlaveActingMasterIT.java
Labels: type/bug

#4843 [ISSUE #4842]fix thread-safety problem of admin tools
  common/src/main/java/org/apache/rocketmq/common/admin/ConsumeStats.java
  common/src/main/java/org/apache/rocketmq/common/admin/TopicStatsTable.java
  common/src/main/java/org/apache/rocketmq/common/protocol/body/TopicList.java
  tools/src/main/java/org/apache/rocketmq/tools/admin/DefaultMQAdminExtImpl.java
Labels: module/admin

#4692 [ISSUE #4584] Add new persist method to update consume offset to remote server.
  client/src/main/java/org/apache/rocketmq/client/consumer/DefaultMQPullConsumer.java
Labels: type/bug, module/client, LTS 4.9.x

#4820 [ISSUE #4805]In the subscribe mode, user-defined MessageQueueListener is supported. At the same time, you can specify the offset that the MessageQueue will commit
  client/src/main/java/org/apache/rocketmq/client/consumer/DefaultLitePullConsumer.java
  client/src/main/java/org/apache/rocketmq/client/consumer/LitePullConsumer.java
  client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultLitePullConsumerImpl.java
  client/src/test/java/org/apache/rocketmq/client/consumer/DefaultLitePullConsumerTest.java
Labels: type/enhancement, module/client

#4883 [ISSUE 4870]Update required status check
  .asf.yaml
Labels: type/enhancement

#4886 [ISSUE 4885]Refine test size of test module
  test/BUILD.bazel
Labels: type/enhancement

#4569 [ISSUE #4568]Improve performance of consume queue
  store/src/main/java/org/apache/rocketmq/store/ConsumeQueue.java
  store/src/test/java/org/apache/rocketmq/store/ConsumeQueueTest.java
Labels: type/enhancement

#4896 [ISSUE #4841] Fix the reply message is the original request msg.
  client/src/main/java/org/apache/rocketmq/client/impl/producer/DefaultMQProducerImpl.java
  client/src/test/java/org/apache/rocketmq/client/producer/DefaultMQProducerTest.java
Labels: LTS 4.9.x
