Repository apache/rocketmq, pull requests merged in 2022-06, with the labels that each got.

#4338 [ISSUE #4226] Message length exceeds the maximum length when sendback
  broker/src/main/java/org/apache/rocketmq/broker/processor/EndTransactionProcessor.java
  client/src/main/java/org/apache/rocketmq/client/producer/DefaultMQProducer.java
  docs/cn/best_practice.md
  docs/cn/client/java/API_Reference_DefaultMQProducer.md
  docs/en/Configuration_Client.md
  docs/en/client/java/API_Reference_DefaultMQProducer.md
  store/src/main/java/org/apache/rocketmq/store/CommitLog.java
  store/src/main/java/org/apache/rocketmq/store/config/MessageStoreConfig.java
  store/src/main/java/org/apache/rocketmq/store/dledger/DLedgerCommitLog.java
  store/src/test/java/org/apache/rocketmq/store/AppendCallbackTest.java
  store/src/test/java/org/apache/rocketmq/store/MultiDispatchTest.java
Labels: progress/discuss

#4417 [ISSUE #4416] Update dledger version to 0.2.6
  pom.xml
Labels: type/enhancement

#4473 Generate legal JSON response conditionally
  common/src/main/java/org/apache/rocketmq/common/protocol/header/namesrv/GetRouteInfoRequestHeader.java
  namesrv/src/main/java/org/apache/rocketmq/namesrv/processor/DefaultRequestProcessor.java
Labels: progress/discuss, API/Protocol Compatibility
