Repository apache/rocketmq, pull requests merged in 2022-09, with the labels that each got.

#4881 send async,time calculation rules Multiple method patches
  client/src/main/java/org/apache/rocketmq/client/impl/producer/DefaultMQProducerImpl.java
Labels: type/enhancement

#5000 [ISSUE#4949] fix Address already in use
  test/src/test/java/org/apache/rocketmq/test/autoswitchrole/AutoSwitchRoleBase.java
  test/src/test/java/org/apache/rocketmq/test/autoswitchrole/AutoSwitchRoleIntegrationTest.java
Labels: type/enhancement

#4925 [ISSUE #4905] Close stale issues/PRs
  .github/workflows/stale.yml
Labels: Prior Discussion Required

#5117 [ISSUE #5116]Make PlainAccessControlFlowTest portable
  acl/BUILD.bazel
  acl/pom.xml
  acl/src/main/java/org/apache/rocketmq/acl/plain/PlainPermissionManager.java
  acl/src/test/java/org/apache/rocketmq/acl/plain/AclTestHelper.java
  acl/src/test/java/org/apache/rocketmq/acl/plain/PlainAccessControlFlowTest.java
Labels: Infra Enhancement Project

#5120 [ISSUE #5119]Infra enhancement project: Fix remaining test cases in ACL module
  acl/BUILD.bazel
  acl/src/test/java/org/apache/rocketmq/acl/plain/AclTestHelper.java
  acl/src/test/java/org/apache/rocketmq/acl/plain/PlainAccessValidatorTest.java
  acl/src/test/java/org/apache/rocketmq/acl/plain/PlainPermissionManagerTest.java
Labels: Infra Enhancement Project

#5185 [ISSUE #5138] Do not throw exception in order producer demo
  example/src/main/java/org/apache/rocketmq/example/ordermessage/Producer.java
Labels: type/code style

#5118 [ISSUE #5121]Add GitHub Action Pipeline to automate release of RocketMQ Snapshots
  .github/asf-deploy-settings.xml
  .github/workflows/snapshot-automation.yml
Labels: Infra Enhancement Project
