Repository apache/rocketmq, pull requests merged in 2022-07, with the labels that each got.

#4516 [ISSUE #4515] Remove implement
  broker/src/main/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessor.java
  broker/src/main/java/org/apache/rocketmq/broker/processor/ClientManageProcessor.java
  broker/src/main/java/org/apache/rocketmq/broker/processor/ConsumerManageProcessor.java
  broker/src/main/java/org/apache/rocketmq/broker/processor/EndTransactionProcessor.java
  broker/src/main/java/org/apache/rocketmq/broker/processor/ForwardRequestProcessor.java
  broker/src/main/java/org/apache/rocketmq/broker/processor/PullMessageProcessor.java
  broker/src/main/java/org/apache/rocketmq/broker/processor/QueryMessageProcessor.java
  broker/src/main/java/org/apache/rocketmq/broker/processor/ReplyMessageProcessor.java
  broker/src/main/java/org/apache/rocketmq/broker/processor/SendMessageProcessor.java
Labels: type/code style

#4500 Fix static topic test, await the client metadata to be refreshed
  .travis.yml
  test/src/main/java/org/apache/rocketmq/test/util/MQAdminTestUtils.java
  test/src/test/java/org/apache/rocketmq/test/base/BaseConf.java
  test/src/test/java/org/apache/rocketmq/test/statictopic/StaticTopicIT.java
Labels: Improvement Required

#4118 [RIP 30] Support Compaction topic
  .gitignore
  broker/src/main/java/org/apache/rocketmq/broker/processor/SendMessageProcessor.java
  common/src/main/java/org/apache/rocketmq/common/TopicAttributes.java
  common/src/main/java/org/apache/rocketmq/common/attribute/DeletePolicy.java
  common/src/main/java/org/apache/rocketmq/common/message/MessageDecoder.java
  common/src/main/java/org/apache/rocketmq/common/utils/DeletePolicyUtils.java
  docs/cn/Example_Compaction_Topic_cn.md
  docs/en/Example_Compaction_Topic.md
  store/src/main/java/org/apache/rocketmq/store/AppendMessageResult.java
  store/src/main/java/org/apache/rocketmq/store/CommitLog.java
  store/src/main/java/org/apache/rocketmq/store/CompactionAppendMsgCallback.java
  store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java
  store/src/main/java/org/apache/rocketmq/store/GetMessageResult.java
  store/src/main/java/org/apache/rocketmq/store/MappedFileQueue.java
  store/src/main/java/org/apache/rocketmq/store/MessageExtEncoder.java
  store/src/main/java/org/apache/rocketmq/store/MultiPathMappedFileQueue.java
  store/src/main/java/org/apache/rocketmq/store/config/MessageStoreConfig.java
  store/src/main/java/org/apache/rocketmq/store/dledger/DLedgerCommitLog.java
  store/src/main/java/org/apache/rocketmq/store/kv/CommitLogDispatcherCompaction.java
  store/src/main/java/org/apache/rocketmq/store/kv/CompactionLog.java
  store/src/main/java/org/apache/rocketmq/store/kv/CompactionPositionMgr.java
  store/src/main/java/org/apache/rocketmq/store/kv/CompactionService.java
  store/src/main/java/org/apache/rocketmq/store/kv/CompactionStore.java
  store/src/main/java/org/apache/rocketmq/store/logfile/DefaultMappedFile.java
  store/src/main/java/org/apache/rocketmq/store/logfile/MappedFile.java
  store/src/main/java/org/apache/rocketmq/store/queue/BatchConsumeQueue.java
  store/src/main/java/org/apache/rocketmq/store/queue/SparseConsumeQueue.java
  store/src/test/java/org/apache/rocketmq/store/AppendCallbackTest.java
  store/src/test/java/org/apache/rocketmq/store/MappedFileQueueTest.java
  store/src/test/java/org/apache/rocketmq/store/kv/CompactionLogTest.java
  store/src/test/java/org/apache/rocketmq/store/kv/CompactionPositionMgrTest.java
  store/src/test/java/org/apache/rocketmq/store/kv/OffsetMapTest.java
  store/src/test/java/org/apache/rocketmq/store/logfile/DefaultMappedFileTest.java
  store/src/test/java/org/apache/rocketmq/store/queue/SparseConsumeQueueTest.java
Labels: module/broker, module/store, type/new feature, type/rip

#4577 [ISSUE #4576] Upgrade dledger version to 0.2.7
  pom.xml
Labels: type/enhancement, module/store, LTS 4.9.x

#4580 [ISSUE #4579] Fix compare different types
  acl/src/main/java/org/apache/rocketmq/acl/plain/PlainPermissionManager.java
Labels: type/bug, module/acl, LTS 4.9.x

#4629 [ISSUE #4628] Fix bug in LMQ when checking multiple Dispatch Queue
  store/src/main/java/org/apache/rocketmq/store/ConsumeQueue.java
Labels: LTS 4.9.x

#4657 [ISSUE #4644] Fix mqadmin deleteTopic bug when command exec on slave broker
  tools/src/main/java/org/apache/rocketmq/tools/command/topic/DeleteTopicSubCommand.java
Labels: LTS 4.9.x

#4666 [ISSUE #4667] Optimizing documents and readme enables users to better use the controller mode
  README.md
  docs/cn/README.md
  docs/cn/controller/deploy.md
  docs/cn/controller/quick_start.md
  docs/cn/image/controller/controller_design_2.png
Labels: module/doc
