Repository apache/rocketmq, pull requests merged in 2023-03, with the labels that each got.

#6068 [ISSUE #6060]Optimize AutoSwitchRoleBase#nextPort method
  test/src/test/java/org/apache/rocketmq/test/autoswitchrole/AutoSwitchRoleBase.java
Labels: Good First Issue

#6317 [ISSUE #6316] Nameserver should choose a master with a larger epoch when there are two masters in controller mode
  broker/src/main/java/org/apache/rocketmq/broker/BrokerController.java
  broker/src/main/java/org/apache/rocketmq/broker/controller/ReplicasManager.java
  broker/src/main/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessor.java
  broker/src/main/java/org/apache/rocketmq/broker/subscription/SubscriptionGroupManager.java
  broker/src/main/java/org/apache/rocketmq/broker/topic/TopicConfigManager.java
  store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java
  store/src/main/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHAService.java
Labels: module/ha, module/controller

#5798 [ISSUE #5663] Fix Messages may be lost when SyncStateSet expand in extreme scenarios
  store/src/main/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHAService.java
  store/src/test/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHATest.java
Labels: module/ha
