Repository apache/rocketmq, pull requests merged in 2023-02, with the labels that each got.

#6070 [ISSUE #6069]Fix README.md DLedger Controller link url incorrect
  README.md
Labels: module/doc

#6042 Polish the unified remoting logger name.
  common/src/main/java/org/apache/rocketmq/common/constant/LoggerName.java
  proxy/src/main/java/org/apache/rocketmq/proxy/remoting/protocol/http2proxy/Http2ProtocolProxyHandler.java
  proxy/src/main/java/org/apache/rocketmq/proxy/remoting/protocol/http2proxy/Http2ProxyBackendHandler.java
  proxy/src/main/java/org/apache/rocketmq/proxy/remoting/protocol/http2proxy/Http2ProxyFrontendHandler.java
  remoting/src/main/java/org/apache/rocketmq/remoting/common/RemotingHelper.java
  remoting/src/main/java/org/apache/rocketmq/remoting/common/ServiceThread.java
  remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyDecoder.java
  remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyEncoder.java
  remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingAbstract.java
  remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingClient.java
  remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingServer.java
  remoting/src/main/java/org/apache/rocketmq/remoting/netty/TlsHelper.java
  remoting/src/main/java/org/apache/rocketmq/remoting/protocol/RemotingCommand.java
Labels: Good First Issue, log

#6146 [ISSUE #6145] modify Collections.sort usage
  broker/src/main/java/org/apache/rocketmq/broker/longpolling/PopRequest.java
  remoting/src/main/java/org/apache/rocketmq/remoting/protocol/statictopic/TopicQueueMappingUtils.java
  remoting/src/main/java/org/apache/rocketmq/remoting/rpc/ClientMetadata.java
  test/src/main/java/org/apache/rocketmq/test/schema/SchemaTools.java
  test/src/main/java/org/apache/rocketmq/test/util/TestUtil.java
  test/src/test/java/org/apache/rocketmq/test/statictopic/StaticTopicIT.java
Labels: type/code style
